---
 - name: update services
   hosts: localhost

   vars:
       DOCKER_VERSION: "{{ lookup('env', 'petclinic') }}"

   tasks:
      - name: Update a Service object
        kubernetes.core.k8s:
          state: present
          definition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              labels:
                app: petclinic
              name: petclinic
              namespace: 4petclinic
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: petclinic
              template:
                metadata:
                  labels:
                    app: petclinic
                spec:
                  containers:
                  - image: "{{ DOCKER_VERSION }}"
                    name: petclinic
                    ports:
                    - containerPort: 8080


